M48
; DRILL file {KiCad 6.0.5-a6ca702e91~116~ubuntu22.04.1} date Fri 10 Jun 2022 04:27:19 PM CDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-10T16:27:19-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.5-a6ca702e91~116~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X4.9162Y-3.2724
X5.1438Y-3.2724
T0
M30
